"""Add source_type to leaflets

Revision ID: b3b7bc3abea0
Revises: e15fd0428f23
Create Date: 2026-01-28 23:59:11.871760+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3b7bc3abea0'
down_revision: Union[str, None] = 'e15fd0428f23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with server default for existing rows, then remove default
    op.add_column('leaflets', sa.Column('source_type', sa.Enum('pdf', 'images', name='leafletsourcetype', native_enum=False), nullable=False, server_default='pdf', comment='Source type: pdf or images (from ZIP or direct upload)'))
    op.alter_column('leaflets', 'source_type', server_default=None)
    op.alter_column('notification_preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='NOW()',
               existing_comment='Creation timestamp',
               existing_nullable=False)
    op.alter_column('notification_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='NOW()',
               existing_comment='Last update timestamp',
               existing_nullable=False)
    op.alter_column('organization_usage_summaries', 'last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='NOW()',
               existing_comment='When this summary was last updated',
               existing_nullable=False)
    op.alter_column('product_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='NOW()',
               existing_comment='Creation timestamp',
               existing_nullable=False)
    op.alter_column('product_categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='NOW()',
               existing_comment='Last update timestamp',
               existing_nullable=False)
    op.alter_column('retailers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='NOW()',
               existing_comment='Creation timestamp',
               existing_nullable=False)
    op.alter_column('retailers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default='NOW()',
               existing_comment='Last update timestamp',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('retailers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-01-03 17:55:12.031038+00'::timestamp with time zone"),
               existing_comment='Last update timestamp',
               existing_nullable=False)
    op.alter_column('retailers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-01-03 17:55:12.031038+00'::timestamp with time zone"),
               existing_comment='Creation timestamp',
               existing_nullable=False)
    op.alter_column('product_categories', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-01-03 17:55:12.031038+00'::timestamp with time zone"),
               existing_comment='Last update timestamp',
               existing_nullable=False)
    op.alter_column('product_categories', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-01-03 17:55:12.031038+00'::timestamp with time zone"),
               existing_comment='Creation timestamp',
               existing_nullable=False)
    op.alter_column('organization_usage_summaries', 'last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-01-03 17:55:12.031038+00'::timestamp with time zone"),
               existing_comment='When this summary was last updated',
               existing_nullable=False)
    op.alter_column('notification_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-01-03 17:55:12.031038+00'::timestamp with time zone"),
               existing_comment='Last update timestamp',
               existing_nullable=False)
    op.alter_column('notification_preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text("'2026-01-03 17:55:12.031038+00'::timestamp with time zone"),
               existing_comment='Creation timestamp',
               existing_nullable=False)
    op.drop_column('leaflets', 'source_type')
    # ### end Alembic commands ###